### ISSUE TITLE
[Meta] Progression

### ISSUE THREAD

**Issue by chamons** [chamons/ArenaGS#242]
As noted in the [dev log](https://chamons.github.io/ArenaGS/progression.html) progression is the next major feature. 

This issue will track the largest bits of work to get this done, but it'll likely be months of work for it to call come together.

## Skill Tree
- [x] New between fight scene
- [x] Button on it to move to the next scene
- [x] Tab View (at least 2 tabs)
- [x] Button with enabled/disabled view state
- [x] A model of N skills of variable cost, that have dependencies between each
- [x] Layout buttons based upon ^
- [x] Layout contains either auto or manuals lines show dependencies
- [x] Clicking buttons costs points, and provides cards/enables dependent skills
- [x] Need to have larger view, or tooltop showing abilities
- [x] [~Undo button (?) to undo last selection?~](https://github.com/chamons/ArenaGS/issues/245)

## Card Selection
- [x] Cards View
- [x] That you can drag around
- [x] Slots
- [x] That cards can snap into
- [x] And out of 
- [ ] ~Drag card on top of filled slot swapped them~
- [x] Auto sort button

## Character Generation from Selections
- [x] Get rid of global skills, make the skills stored on each character 
- [x] Dynamic skill creation based upon cards (since we can modify cost/range/etc)
- [x] Start with a 'blank' character
- [x] Based upon cards, build up skills and stats

## Gaining cards between fight
- [x] Before moving to skill tree/selection, have a reward screen
- [x] Show 2-3 cards
- [x] Show cash out button
- [x] Allow selecting one

## Shop for spending currency
- [x] Somehow (random event, 3rd tab?) add a shop
- [x] Spend currency to select cards
- [x] Add extra slot for purchase (and somehow from skill tree?)
- [x] Randomly generate shop every visit/round based upon pool
- [x] Cards like need rarity to make this make sense

## Combat Tab
- [x] Add tab 
- [x] Show skillbar and stats 
- [x] Button to move to next battle

## Wrapping up
- [x] Add first pass of gunslinger skills
- [x] [Confirm Skill Tree Selection](https://github.com/chamons/ArenaGS/issues/256)
- [x] [Equipment Sort has long pause](https://github.com/chamons/ArenaGS/issues/255)
- [x] [Skill rename](https://github.com/chamons/ArenaGS/issues/259)
- [x] [Crash](https://github.com/chamons/ArenaGS/issues/262)
- [x] Make help work on all between fight screens
- [x] Add help topics for all of this
- [x] Play testing

**Comment by chamons** [comment]
Success! Now to write a blog post.
